"""
Renders AgentPlanSubmission into human-readable plan artifacts and converts
it into a PlanningResult.

Public API
----------
render_plan_context      — per-criterion plan_context string for PlannedCriterion
render_agent_full_plan   — full planning report → .tdd-plan.md content
render_agent_gap_plan    — remaining-work gap plan → .gap-plan.md content
build_agent_diagnostics  — assumptions and validation notes → PlanningDiagnostic tuple
to_planning_result       — AgentPlanSubmission → PlanningResult

The authoritative live result is the validated structured submission
converted via to_planning_result(). The markdown artifacts are
human-readable auditing aids; no downstream component may parse them
for metadata.
"""

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .agent_models import AgentCriterionAssessment, AgentPlanSubmission
    from .models import PlanningDiagnostic, PlanningResult


def render_plan_context(assessment: "AgentCriterionAssessment") -> str:
    """
    Deterministically render a plan_context string for one criterion.

    The string is composed from rationale, evidence, planned changes,
    verification mode, existing test refs, and any free-text plan_context.
    No downstream component may parse this string for metadata.
    """
    parts: list[str] = []

    if assessment.plan_context:
        parts.append(assessment.plan_context)

    if assessment.rationale:
        parts.append(f"Rationale: {assessment.rationale}")

    if assessment.evidence:
        lines = []
        for ev in assessment.evidence:
            if ev.path:
                lines.append(f"- [{ev.path}] {ev.observation}")
            else:
                lines.append(f"- {ev.observation}")
        parts.append("Evidence:\n" + "\n".join(lines))

    if assessment.planned_changes:
        lines = []
        for c in assessment.planned_changes:
            sym = f" (symbols: {', '.join(c.symbols)})" if c.symbols else ""
            lines.append(f"- {c.path}: {c.description}{sym}")
        parts.append("Planned changes:\n" + "\n".join(lines))

    if assessment.verification:
        parts.append(f"Verification: {assessment.verification}")

    if assessment.existing_test_refs:
        parts.append("Existing tests: " + "; ".join(assessment.existing_test_refs))

    if assessment.blocker:
        parts.append(f"Blocker: {assessment.blocker}")

    return "\n\n".join(parts)


def render_agent_full_plan(submission: "AgentPlanSubmission") -> str:
    """
    Render the complete agent planning report.

    This content is written to .tdd-plan.md.  It includes both satisfied
    and remaining criteria so that all planning decisions are auditable.
    """
    today = date.today().isoformat()
    sections: list[str] = [
        f"<!-- generated by AgentPlanningStrategy on {today} -->"
    ]

    sections.append("# Agent Planning Report")
    sections.append(f"## Ticket Summary\n\n{submission.ticket_summary}")
    sections.append(f"## Approach\n\n{submission.approach_summary}")

    if submission.repository_findings:
        lines = []
        for ev in submission.repository_findings:
            if ev.path:
                lines.append(f"- `{ev.path}`: {ev.observation}")
            else:
                lines.append(f"- {ev.observation}")
        sections.append("## Repository Findings\n\n" + "\n".join(lines))

    if submission.assumptions:
        lines = []
        for a in submission.assumptions:
            lines.append(f"- **{a.question}**: {a.answer} *(basis: {a.basis})*")
        sections.append("## Assumptions\n\n" + "\n".join(lines))

    # Criterion Assessments — all dispositions
    criterion_blocks: list[str] = []
    for assessment in submission.criteria:
        block_lines: list[str] = [
            f"### {assessment.criterion_id}: {assessment.disposition.upper()}",
            "",
            f"**Criterion:** {assessment.source_criterion}",
            "",
            f"**Rationale:** {assessment.rationale}",
        ]
        if assessment.evidence:
            block_lines.append("")
            block_lines.append("**Evidence:**")
            for ev in assessment.evidence:
                prefix = f"`{ev.path}`" if ev.path else "(general)"
                block_lines.append(f"- {prefix}: {ev.observation}")
        if assessment.planned_changes:
            block_lines.append("")
            block_lines.append("**Planned changes:**")
            for c in assessment.planned_changes:
                sym = f" ({', '.join(c.symbols)})" if c.symbols else ""
                block_lines.append(f"- `{c.path}`: {c.description}{sym}")
        if assessment.verification:
            block_lines.append(f"\n**Verification:** {assessment.verification}")
        if assessment.implementation_strategy:
            block_lines.append(
                f"**Implementation strategy:** {assessment.implementation_strategy}"
            )
        if assessment.existing_test_refs:
            refs = "; ".join(assessment.existing_test_refs)
            block_lines.append(f"**Existing tests:** {refs}")
        if assessment.blocker:
            block_lines.append(f"\n**Blocker:** {assessment.blocker}")
        criterion_blocks.append("\n".join(block_lines))

    sections.append("## Criterion Assessments\n\n" + "\n\n".join(criterion_blocks))

    if submission.cross_cutting_changes:
        lines = [
            f"- `{c.path}`: {c.description}"
            for c in submission.cross_cutting_changes
        ]
        sections.append("## Cross-Cutting Changes\n\n" + "\n".join(lines))

    if submission.risks:
        lines = [f"- {r}" for r in submission.risks]
        sections.append("## Risks\n\n" + "\n".join(lines))

    # Implementation Plan — remaining only
    remaining = [a for a in submission.criteria if a.disposition == "remaining"]
    if remaining:
        impl_lines: list[str] = []
        for assessment in remaining:
            impl_lines.append(f"### {assessment.criterion_id}")
            for c in assessment.planned_changes:
                impl_lines.append(f"- `{c.path}`: {c.description}")
        sections.append("## Implementation Plan\n\n" + "\n".join(impl_lines))

    # Verification Plan — remaining only
    if remaining:
        ver_lines: list[str] = []
        for assessment in remaining:
            ver = assessment.verification or "test"
            strategy = assessment.implementation_strategy or "tdd"
            ver_lines.append(
                f"- {assessment.criterion_id}: verify={ver}, strategy={strategy}"
            )
            for ref in assessment.existing_test_refs:
                ver_lines.append(f"  - existing: {ref}")
        sections.append("## Verification Plan\n\n" + "\n".join(ver_lines))

    return "\n\n".join(sections) + "\n"


def render_agent_gap_plan(submission: "AgentPlanSubmission") -> str:
    """
    Render the gap plan containing only remaining work.

    This content is written to .gap-plan.md.  The format is designed for
    compatibility with --from-gap-plan where practical.
    """
    today = date.today().isoformat()
    sections: list[str] = [
        f"<!-- narrowed by AgentPlanningStrategy on {today} -->"
    ]

    sections.append("## Source\n\nAgent-first planning strategy.")

    remaining = [a for a in submission.criteria if a.disposition == "remaining"]

    if not remaining:
        sections.append(
            "## Acceptance Criteria\n\n(none - all criteria satisfied)"
        )
    else:
        criteria_lines: list[str] = []
        for assessment in remaining:
            ver = assessment.verification or "test"
            tags = f"verify: {ver}"
            if assessment.implementation_strategy:
                tags += f"; strategy: {assessment.implementation_strategy}"
            for ref in assessment.existing_test_refs:
                tags += f"; existing_test: {ref}"
            criteria_lines.append(
                f"- [ ] {assessment.source_criterion} <!-- {tags} -->"
            )
        sections.append("## Acceptance Criteria\n\n" + "\n".join(criteria_lines))

        impl_lines: list[str] = []
        for assessment in remaining:
            for change in assessment.planned_changes:
                impl_lines.append(f"- `{change.path}`: {change.description}")
        if impl_lines:
            sections.append("## Implementation Plan\n\n" + "\n".join(impl_lines))

    return "\n\n".join(sections) + "\n"


def build_agent_diagnostics(
    submission: "AgentPlanSubmission",
) -> "tuple[PlanningDiagnostic, ...]":
    """Convert AgentPlanSubmission assumptions and notes into PlanningDiagnostic entries."""
    from .models import PlanningDiagnostic

    diagnostics: list[PlanningDiagnostic] = []

    for assumption in submission.assumptions:
        diagnostics.append(
            PlanningDiagnostic(
                level="info",
                message=(
                    f"Assumption — {assumption.question}: "
                    f"{assumption.answer} (basis: {assumption.basis})"
                ),
                code="agent_assumption",
            )
        )

    for note in submission.validation_notes:
        diagnostics.append(
            PlanningDiagnostic(
                level="warning",
                message=note,
                code="agent_validation_note",
            )
        )

    return tuple(diagnostics)


def to_planning_result(submission: "AgentPlanSubmission") -> "PlanningResult":
    """
    Convert a validated AgentPlanSubmission into a PlanningResult.

    Only 'remaining' assessments become PlannedCriterion values.
    Satisfied, not_applicable, and blocked assessments are preserved
    in the human-readable plan text but do not enter the criteria stack.
    """
    from .models import PlannedCriterion, PlanningResult

    remaining = tuple(
        PlannedCriterion(
            criterion=assessment.source_criterion,
            plan_context=render_plan_context(assessment),
            verification=assessment.verification or "test",
            implementation_strategy=(
                assessment.implementation_strategy or "tdd"
            ),
            existing_test_refs=assessment.existing_test_refs,
        )
        for assessment in submission.criteria
        if assessment.disposition == "remaining"
    )

    return PlanningResult(
        criteria=remaining,
        plan_text=render_agent_full_plan(submission),
        narrowed_plan_text=render_agent_gap_plan(submission),
        diagnostics=build_agent_diagnostics(submission),
    )
